### PR TITLE
Add fuzz targets for semver.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by killercup** [comment]
Very nice! `version_req_read_write_read` immediately (just 127,034 iterations 😅) found the bug you already reported. Good job at minimizing it, the base case I got was `111111111111111111.*.1`.

Travis failure seems related to rustfmt-targets and not this.

**Comment by frewsxcv** [comment]
> Good job at minimizing it

FYI, there's a `minimize_crash=1 <crash file name>` flag for libfuzzer you can use to minimize a crash

**Comment by killercup** [comment]
Really? :O TIL

**Comment by frewsxcv** [comment]
You should be able to do something like this:

```diff
diff --git a/run-fuzzer.sh b/run-fuzzer.sh
index 7e58a5f..87c337b 100755
--- a/run-fuzzer.sh
+++ b/run-fuzzer.sh
@@ -47,4 +47,5 @@ else
     exit 1
 fi
 
-cargo run --target $TARGET --bin "$2" -- ${@:3} `pwd`/corpus `pwd`/seeds
+# cargo run --target $TARGET --bin "$2" -- ${@:3} `pwd`/corpus `pwd`/seeds
+cargo run --target $TARGET --bin "$2" -- ${@:3} -minimize_crash = 1 ./crash-1e14de261fd235a653f7a52c5eeed03f9dbfda80
```

Lemme know if you run into any issues and I can try to help

**Comment by killercup** [comment]
Very cool! I've read through `-help` but probably missed minimize.

Sadly I fixed all my crashes except for an OOM and it's not doing anything useful for that it seems :(

**Pull request merged**
