### PR TITLE
Add fuzz target for cssparser crate.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
@Manishearth @nagisa I'm getting an error locally when compiling this:

```
corey@debian:~/dev/targets/cssparser$ echo $RUSTFLAGS 
-Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort
corey@debian:~/dev/targets/cssparser$ cargo build
   Compiling cssparser-macros v0.2.0 (https://github.com/servo/rust-cssparser.git#6fe264ee)
error: Only executables and rlibs can be compiled with `-Z sanitizer`

error: aborting due to previous error

error: Could not compile `cssparser-macros`.

To learn more, run the command again with --verbose.
```

Thoughts? I assume that we can't compile macro crates (or whatever this is) with the `-Z sanitizer` flag. Is there any easy way around this to avoid this papercut for other users?

**Comment by Manishearth** [comment]
Pass --target x86_64-unknown-linux-gnu to cargo

While you're at it, set the ASAN_OPTIONS that cargo-fuzz sets too.

**Comment by frewsxcv** [comment]
@Manishearth Want to try an r+ here?

**Comment by Manishearth** [comment]
bors: r+

**Comment by notriddle** [comment]
Try it again, @Manishearth. Without the colon.

**Pull request merged**
